die when starved for work

diff --git a/bin/nu_pkg_build_cluster b/bin/nu_pkg_build_cluster
--- a/bin/nu_pkg_build_cluster
+++ b/bin/nu_pkg_build_cluster
@@ -44,23 +44,26 @@ done
 (cd "${CHROOTDIR-}$PKG_DBDIR" && tar -cf - */dependencies */dependants | tar -xf - -C "$data_graph")
 
 getwork () {
+	local _retvar=$1 _port= _idle=
 	[ -n "`cd "$data_graph" && find . -depth 1 -name '*_*' | head -n 1`" ] || return 1
-	local port= idle=
-	while [ -z "$port" ]; do
-		port=`cd "$data_graph" && find . -name dependencies -and -empty 2> /dev/null | sed -Ee 's%./([^_]+)_(.*)/dependencies%\1/\2%' | head -n 1`
-		if [ -z "$port" ]; then
+	while [ -z "$_port" ]; do
+		_port=`cd "$data_graph" && find . -name dependencies -and -empty 2> /dev/null | sed -Ee 's%./([^_]+)_(.*)/dependencies%\1/\2%' | head -n 1`
+		if [ -z "$_port" ]; then
 			if [ -n "`find "$workers" -depth 2 -type d`" ]; then
-				idle=
+				_idle=
 			else
-				incr idle 0 3 || (echo "Starved for work. See errors in $logs." >&2 && exit 1)
+				if ! incr _idle 0 3; then
+					echo "Starved for work. See errors in $logs." >&2
+					exit 1
+				fi
 			fi
 			sleep 1
 		fi
 	done
-	echo $port
+	setvar $_retvar $_port
 }
 
-while port=`getwork`; do
+while getwork port; do
 	port_=`echo $port | tr / _`
 	worker=
 	while [ -z "$worker" ]; do
