a few minor improvements

diff --git a/bin/nu_vm b/bin/nu_vm
--- a/bin/nu_vm
+++ b/bin/nu_vm
@@ -18,18 +18,20 @@ NUOS_VER=0.0.9.3b0
 
 . "$(dirname "$(realpath "$0")")/../lib/nu_system.sh"
 
-while getopts c:C:d:D:fh:ij:lLo:sSv OPT; do case $OPT in
+while getopts c:C:d:Dfh:ij:lLm:o:OsSv OPT; do case $OPT in
 	c) NUM_CPUS=$OPTARG;;
 	C) CHROOTDIR=$OPTARG;;
-	d) push VM_HDDS $OPTARG;;
-	D) push VM_HDDS_NEW $OPTARG;;
+	d) push VM_HDDS ${OPTARG#/dev/};;
+	D) OPT_DELETE=y;;
 	f) OPT_FORCE=y;;
 	h) HOST_NAME=$OPTARG;;
 	i) OPT_INIT=y;;
 	j) VM_NAME=$OPTARG;;
-	o) OS_TYPE=$OPTARG;;
 	l) OPT_LIST_RUNNING=y;;
 	L) OPT_LIST_ALL=y;;
+	m) VM_MEM_MB=$OPTARG;;
+	o) OS_TYPE=$OPTARG;;
+	O) OPT_LIST_OS_TYPES=y;;
 	s) OPT_START=y;;
 	S) OPT_STOP=y;;
 	v) OPT_VERBOSE=y;;
@@ -40,7 +42,9 @@ esac; done; shift $(($OPTIND-1))
 
 . "$(dirname "$(realpath "$0")")/../lib/nu_common.sh"
 
-MAX_VM_DISKS=24
+: ${VM_NAME:=box}
+: ${MAX_VM_DISKS:=24}
+: ${CHIPSET:=ich9} # can set to piix3
 
 if [ -n "${OPT_LIST_RUNNING-}" ]; then
 	VBoxManage list runningvms | cut -w -f 1 | xargs
@@ -50,8 +54,10 @@ if [ -n "${OPT_LIST_ALL-}" ]; then
 	VBoxManage list vms | cut -w -f 1 | xargs
 	exit 0
 fi
-
-nuos_init
+if [ -n "${OPT_LIST_OS_TYPES-}" ]; then
+	VBoxManage list ostypes | grep ^ID: | cut -w -f 2 | xargs
+	exit 0
+fi
 
 if [ -n "${OPT_INIT-}" ]; then
 	kldload vboxdrv
@@ -63,11 +69,14 @@ EOF
 	echo "Configured vm service."
 	exit 0
 fi
-: ${VM_NAME:=box}
 
 if [ -n "${OPT_START-}" ]; then
-	[ -z "${OPT_STOP-}" ]
-	VBoxManage startvm "$VM_NAME" --type headless
+	if [ -n "${OPT_STOP-}" ]; then
+		[ -n "${OPT_FORCE-}" ] || (echo 'Error: You must also specify the -f flag (OPT_FORCE) to perform a hard reset.' && exit 1)
+		VBoxManage controlvm "$VM_NAME" reset
+	else
+		VBoxManage startvm "$VM_NAME" --type headless
+	fi
 	exit 0
 elif [ -n "${OPT_STOP-}" ]; then
 	if [ -n "${OPT_FORCE-}" ]; then
@@ -76,7 +85,14 @@ elif [ -n "${OPT_STOP-}" ]; then
 		VBoxManage controlvm "$VM_NAME" acpipowerbutton
 	fi
 	exit 0
+elif [ -n "${OPT_DELETE-}" ]; then
+	[ -n "${OPT_FORCE-}" ] || (echo 'Error: You must also specify the -f flag (OPT_FORCE) to delete a vm.' && exit 1)
+	VBoxManage unregistervm "$VM_NAME" --delete
+	echo "Deleted vm $VM_NAME successfully."
+	exit 0
 fi
+
+nuos_init
 
 echo 'creating vm     -j VM_NAME        ' $VM_NAME
 #echo 'host name       -h HOST_NAME      ' ${HOST_NAME:=$VM_NAME.$HOST}
@@ -84,8 +100,6 @@ echo 'num cpus        -c VM_CPUS        ' ${VM_CPUS:=`sysctl -n kern.smp.cpus`}
 echo 'mem megabytes   -m VM_MEM_MB      ' ${VM_MEM_MB:=1024}
 echo 'os type         -o OS_TYPE        ' ${OS_TYPE:=FreeBSD_64}
 echo -n 'connect hdds    -d VM_HDDS         ' && [ -n "${VM_HDDS-}" ] && echo $VM_HDDS || echo null
-echo -n 'new hdds        -D VM_HDDS_NEW     ' && [ -n "${VM_HDDS_NEW-}" ] && echo $VM_HDDS_NEW || echo null
-#echo 'host name       -h HOST_NAME      ' ${HOST_NAME:=$HOST}
 echo
 
 maybe_yell
@@ -93,10 +107,13 @@ maybe_yell
 [ "$USER" != root ]
 
 VBoxManage createvm --name "$VM_NAME" --ostype "$OS_TYPE" --register
-VBoxManage modifyvm "$VM_NAME" --rtcuseutc on --hwvirtex on --chipset ich9 --ioapic on --hpet on --cpus "$VM_CPUS" --memory "$VM_MEM_MB" --mouse usb --keyboard usb
+VBoxManage modifyvm "$VM_NAME" --rtcuseutc on --hwvirtex on --ioapic on --chipset $CHIPSET --hpet on --cpus "$VM_CPUS" --memory "$VM_MEM_MB" --mouse usb --keyboard usb
 VBoxManage storagectl "$VM_NAME" --name sata0 --add sata --controller IntelAhci --portcount $MAX_VM_DISKS
-for disk in $VM_HDDS; do
-	incr disk_i 0 $MAX_VM_DISKS
-	VBoxManage internalcommands createrawvmdk -filename ~/"VirtualBox VMs/$VM_NAME/sata0_port$disk_i.vmdk" -rawdisk /dev/$disk
-	VBoxManage storageattach "$VM_NAME" --storagectl sata0 --type hdd --nonrotational on --port $disk_i --device 0 --medium ~/"VirtualBox VMs/$VM_NAME/sata0_port$disk_i.vmdk"
-done
+if [ -n "${VM_HDDS-}" ]; then
+	for disk in $VM_HDDS; do
+		incr disk_i 0 $MAX_VM_DISKS
+		VBoxManage internalcommands createrawvmdk -filename ~/"VirtualBox VMs/$VM_NAME/sata0_port$disk_i.vmdk" -rawdisk /dev/$disk
+		VBoxManage storageattach "$VM_NAME" --storagectl sata0 --type hdd --nonrotational on --discard on --port $disk_i --device 0 --medium ~/"VirtualBox VMs/$VM_NAME/sata0_port$disk_i.vmdk"
+	done
+fi
+echo "Configured vm $VM_NAME successfully."
